### ISSUE TITLE
Investigate skunk compilation error after upgrading to 1.0.0-RC2

### ISSUE THREAD

**Issue by mpilquist** [typelevel/twiddles#146]
```scala
[error] -- [E007] Type Mismatch Error: /home/runner/work/skunk/skunk/modules/core/shared/src/main/scala/AppliedFragment.scala:22:48 
[error] 22 |    AppliedFragment(fragment *: other.fragment, argument *: other.argument *: EmptyTuple)
[error]    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    (AppliedFragment.this.A, other.A)
[error]    |Required: org.typelevel.twiddles.Twiddles.Prepend[AppliedFragment.this.A, other.A]
[error]    |
[error]    |Note: a match type could not be fully reduced:
[error]    |
[error]    |  trying to reduce  org.typelevel.twiddles.Twiddles.Prepend[AppliedFragment.this.A, other.A]
[error]    |  failed since selector other.A
[error]    |  does not match  case Tuple => AppliedFragment.this.A *: other.A
[error]    |  and cannot be shown to be disjoint from it either.
[error]    |  Therefore, reduction cannot advance to the remaining case
[error]    |
[error]    |    case Any => (AppliedFragment.this.A, other.A)
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
[error] (coreJVM / Compile / compileIncremental) Compilation failed
````

We can workaround that error with a cast:
```scala
    AppliedFragment((fragment *: other.fragment).asInstanceOf[Fragment[A *: other.A *: EmptyTuple]], argument *: other.argument *: EmptyTuple)
```

The example project and tests project fail to compile as well though, e.g.:

```scala
[error] -- Error: /Users/mpilqu0037e@cable.comcast.com/Development/oss/skunk/modules/example/src/main/scala/Error.scala:25:4
[error]  25 |    sql"""
[error]     |    ^
[error]     |illegal repeated type application
[error]     |You might have meant something like:
[error]     |skunk.Encoder.twiddlesPrependOps.*:[String, Int *: EmptyTuple.type & Tuple]
[error]  26 |      SELECT name, code
[error]  27 |      FROM   country
[error]  28 |      WHERE  popsulation > $varchar
[error]  29 |      AND    population  < $int4
[error]  30 |    """.query(varchar *: int4)
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from StringContextOps.scala:130
[error] 130 |          encoders.init.foldRight(last) { case ('{$a: Encoder[a]}, '{$acc: Encoder[t & Tuple]}) => '{$a *: $acc} }
[error]     |                                                                                                        ^^
[error]      ---------------------------------------------------------------------------
[error] one error found
```

The example & test issues can be worked around by modifying `StringContextOps` to not use `*:` and instead manually inline its definition:

```scala
encoders.init.foldRight(last) { case ('{$a: Encoder[a]}, '{$acc: Encoder[t & Tuple]}) =>
  // TODO Should be able to use *: but as of twiddles 1.0.0-RC2 that no longer works; see https://github.com/typelevel/twiddles/issues/146
  '{$a.product($acc).imap { case (h, t) => h *: t } { case h *: t => (h, t) } }
}
```

**Comment by aartigao** [comment]
This bug is hitting us in our Skunk app for all the defined codecs.

We have the codecs defined this way:

```scala
    lazy val budgetAllowance: Codec[Budget.Allowance] =
      (
        zoneId *:
        countryId *:
        budgetAllowanceValue *:
        budgetAllowanceValue *:
        budgetAllowanceValue *:
        budgetAllowanceValue *:
        budgetAllowanceValue *:
        budgetAllowanceValue *:
        budgetAllowanceValue
      ).to[Budget.Allowance]
```

Where all referenced instances are valid `Codec[Whatever]`. Since Skunk 1.0.0 this no longer compiles.

**Comment by mpilquist** [comment]
Thanks, do you mind providing a Scala-cli script that reproduces?

**Comment by L7R7** [comment]
I am not sure if this is the same problem, but after upgrading skunk to 1.0.0 I am getting compile errors that look similar. I was able to minimize my case down to opaque types. This worked with skunk 1.0.0-M12:

```scala
import skunk.Codec
import skunk.codec.all.int4

opaque type OpaqueInt = Int

object OpaqueInt:
  val codec: Codec[OpaqueInt] = int4

case class Example(i0: Int, i1: OpaqueInt)

object Example:
  val encoder: Codec[Example] = (int4 *: OpaqueInt.codec).to[Example]
```

with 1.0.0 I get the following error: 

<details>
<summary>compile error</summary>
```
-- [E172] Type Error: /<REDACTED>>/Reproducer.scala:14:60
14 |  val encoder: Codec[Example] = (int4 *: OpaqueInt.codec).to[Example]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |Could not prove org.typelevel.twiddles.Twiddles.Prepend[Int, com.l7r7.lab.OpaqueInt] is isomorphic to com.l7r7.lab.Example..
   |I found:
   |
   |    org.typelevel.twiddles.Iso.inverse[com.l7r7.lab.Example,
   |      org.typelevel.twiddles.Twiddles.Prepend[Int, com.l7r7.lab.OpaqueInt]](
   |      org.typelevel.twiddles.Iso.inverse[
   |        org.typelevel.twiddles.Twiddles.Prepend[Int, com.l7r7.lab.OpaqueInt],
   |        com.l7r7.lab.Example](
   |        org.typelevel.twiddles.Iso.singletonInstance[
   |          org.typelevel.twiddles.Twiddles.Prepend[Int, com.l7r7.lab.OpaqueInt],
   |          com.l7r7.lab.Example](
   |          com.l7r7.lab.Example.$asInstanceOf[
   |
   |              scala.deriving.Mirror.Product{
   |                type MirroredType = com.l7r7.lab.Example;
   |                  type MirroredMonoType = com.l7r7.lab.Example;
   |                  type MirroredElemTypes <: Tuple;
   |                  type MirroredElemTypes =
   |                    org.typelevel.twiddles.Twiddles.Prepend[Int,
   |                      com.l7r7.lab.OpaqueInt]
   |                   *: EmptyTuple
   |              }
   |             &
   |              scala.deriving.Mirror.Product{
   |                type MirroredMonoType = com.l7r7.lab.Example;
   |                  type MirroredType = com.l7r7.lab.Example;
   |                  type MirroredLabel = ("Example" : String);
   |                  type MirroredElemTypes = (Int, com.l7r7.lab.OpaqueInt);
   |                  type MirroredElemLabels = (("i0" : String), ("i1" : String))
   |              }
   |
   |          ]
   |        )
   |      )
   |    )
   |
   |But given instance singletonInstance in object Iso does not match type org.typelevel.twiddles.Iso[
   |  org.typelevel.twiddles.Twiddles.Prepend[Int, com.l7r7.lab.OpaqueInt],
   |  com.l7r7.lab.Example].
   |
   |Note: a match type could not be fully reduced:
   |
   |  trying to reduce  org.typelevel.twiddles.Twiddles.Prepend[Int, com.l7r7.lab.OpaqueInt]
   |  failed since selector com.l7r7.lab.OpaqueInt
   |  does not match  case Tuple => Int *: com.l7r7.lab.OpaqueInt
   |  and cannot be shown to be disjoint from it either.
   |  Therefore, reduction cannot advance to the remaining case
   |
   |    case Any => (Int, com.l7r7.lab.OpaqueInt)
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from Twiddles.scala:77
    ----------------------------------------------------------------------------
one error found
```
</details>

(I posted this on the [Typelevel Discord](https://discord.com/channels/632277896739946517/839844929877704785/1495811391062540429) before I found this here)

**Comment by mpilquist** [comment]
The opaque type issue is definitely caused by the introduction of `Twiddles.Prepend` match type in https://github.com/typelevel/twiddles/pull/140.

**Comment by aartigao** [comment]
I can confirm our issue is with opaque types (we use Neotype library for them). But I guess the issue is not related to the library, judging from the provided example.

**Comment by mpilquist** [comment]
@aartigao Ah, thanks for confirming that. Unfortunately, I think this means we need to roll back the change in #140 but do so in a binary compatible way. Not sure how difficult that will be but will give it a shot.

**Comment by mpilquist** [comment]
Give https://github.com/typelevel/skunk/releases/tag/v1.1.0-RC1 a shot and let me know if things are working again?

**Comment by BenFradet** [comment]
~1.1.0 seems to compile fine, thank you. are there changes needed on the skunk side to move away from prepend?~
seems like it was addressed in skunk 1.1.0-RC1
