### PR TITLE
Restore old implementation of *: on Scala 3 to restore compatibility with opaque types

### LINKED ISSUE #146: Investigate skunk compilation error after upgrading to 1.0.0-RC2
```scala
[error] -- [E007] Type Mismatch Error: /home/runner/work/skunk/skunk/modules/core/shared/src/main/scala/AppliedFragment.scala:22:48 
[error] 22 |    AppliedFragment(fragment *: other.fragment, argument *: other.argument *: EmptyTuple)
[error]    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    (AppliedFragment.this.A, other.A)
[error]    |Required: org.typelevel.twiddles.Twiddles.Prepend[AppliedFragment.this.A, other.A]
[error]    |
[error]    |Note: a match type could not be fully reduced:
[error]    |
[error]    |  trying to reduce  org.typelevel.twiddles.Twiddles.Prepend[AppliedFragment.this.A, other.A]
[error]    |  failed since selector other.A
[error]    |  does not match  case Tuple => AppliedFragment.this.A *: other.A
[error]    |  and cannot be shown to be disjoint from it either.
[error]    |  Therefore, reduction cannot advance to the remaining case
[error]    |
[error]    |    case Any => (AppliedFragment.this.A, other.A)
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
[error] (coreJVM / Compile / compileIncremental) Compilation failed
````

We can workaround that error with a cast:
```scala
    AppliedFragment((fragment *: other.fragment).asInstanceOf[Fragment[A *: other.A *: EmptyTuple]], argument *: other.argument *: EmptyTuple)
```

The example project and tests project fail to compile as well though, e.g.:

```scala
[error] -- Error: /Users/mpilqu0037e@cable.comcast.com/Development/oss/skunk/modules/example/src/main/scala/Error.scala:25:4
[error]  25 |    sql"""
[error]     |    ^
[error]     |illegal repeated type application
[error]     |You might have meant something like:
[error]     |skunk.Encoder.twiddlesPrependOps.*:[String, Int *: EmptyTuple.type & Tuple]
[error]  26 |      SELECT name, code
[error]  27 |      FROM   country
[error]  28 |      WHERE  popsulation > $varchar
[error]  29 |      AND    population  < $int4
[error]  30 |    """.query(varchar *: int4)
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from StringContextOps.scala:130
[error] 130 |          encoders.init.foldRight(last) { case ('{$a: Encoder[a]}, '{$acc: Encoder[t & Tuple]}) => '{$a *: $acc} }
[error]     |                                                                                                        ^^
[error]      ---------------------------------------------------------------------------
[error] one error found
```

The example & test issues can be worked around by modifying `StringContextOps` to not use `*:` and instead manually inline its definition:

```scala
encoders.init.foldRight(last) { case ('{$a: Encoder[a]}, '{$acc: Encoder[t & Tuple]}) =>
  // TODO Should be able to use *: but as of twiddles 1.0.0-RC2 that no longer works; see https://github.com/typelevel/twiddles/issues/146
  '{$a.product($acc).imap { case (h, t) => h *: t } { case h *: t => (h, t) } }
}
```

### PR DESCRIPTION
**Pull request by mpilquist**
Fixes #146.

The implementation of `*:` introduced in #140 relied on a match type:

```scala
type Prepend[A, B] = B match
  case Tuple => A *: B
  case _     => A *: B *: EmptyTuple
```

Given a `Prepend[X, Y]` where `Y` is an opaque type (or like in the original report in #146, an abstract type), the compiler cannot refute that `Y` is a `Tuple` so does no further reduction beyond `Prepend[X, Y]`.

Hence, the technique based on `Prepend` is fundamentally flawed. This PR restores the older implementation based on implicit classes.

### CODE REVIEW

File: core/shared/src/main/scala-3/org/typelevel/twiddles/Twiddles.scala [hunk 1]
```diff
@@ -55,18 +58,23 @@ object Twiddles:
...
+        ??? // Unreachable, kept for bincompat
 
     extension [A, G[x] >: F[x]: InvariantSemigroupal](self: G[A])
       inline def *:[B](that: F[B]): G[Prepend[A, B]] =
-        prepend(self, that)
+        ??? // Unreachable, kept for bincompat
 
 trait TwiddleSyntax[F[_]]:
 
-  given twiddlesPrependOps: Twiddles.PrependOps[F] with {}
```
Comment (mpilquist) [inline core/shared/src/main/scala-3/org/typelevel/twiddles/Twiddles.scala:69]: This is safe to drop completely as its only utility was providing compile time access to the inline extension methods from `PrependOps`.
